# Generated by Django 5.0.4 on 2024-05-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myEvent',
            new_name='my_event',
        ),
    ]
