# Generated by Django 5.0.4 on 2024-05-16 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_myevent_my_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_event',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
