# Generated by Django 5.0.6 on 2024-06-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
    ]
