# Generated by Django 5.0.6 on 2024-05-25 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('boards', '0005_category_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boards.category'),
        ),
    ]
