# Generated by Django 5.0.6 on 2024-05-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='member',
            new_name='category',
        ),
    ]
