# Generated by Django 5.0.6 on 2024-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_friend_receiver_alter_friend_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('1', '等待確認'), ('2', '確認'), ('3', '拒絕')], default='1', max_length=1),
        ),
    ]
