# Generated by Django 5.0.4 on 2024-05-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
