# Generated by Django 5.0.6 on 2024-05-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membertask',
            old_name='members',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='membertask',
            old_name='tasks',
            new_name='task',
        ),
    ]
