# Generated by Django 5.0.4 on 2024-05-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taketask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='situation',
        ),
    ]
