# Generated by Django 5.0.4 on 2024-05-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_taketask_task_remove_task_situation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_user_name',
            new_name='created_user',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='name',
        ),
        migrations.AddField(
            model_name='situation',
            name='col_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.CharField(default='', max_length=1),
        ),
    ]
