# Generated by Django 5.0.4 on 2024-05-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_created_user_name_task_created_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='get_time',
            field=models.DateTimeField(null=True),
        ),
    ]
