# Generated by Django 5.0.6 on 2024-06-09 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatemessage',
            options={},
        ),
    ]
