# Generated by Django 5.0.6 on 2024-06-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_category_member'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
    ]
