# Generated by Django 5.0.6 on 2024-06-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paies',
            name='item_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paies',
            name='merchant_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paies',
            name='notify_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='paies',
            name='return_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='paies',
            name='version',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
