# Generated by Django 5.0.6 on 2024-05-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_like_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='like_sender',
            new_name='like_by',
        ),
    ]
