# Generated by Django 5.0.6 on 2024-05-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('members', '0004_rename_like_sender_member_like_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='liking_article_mambers',
            field=models.ManyToManyField(related_name='liking_article_mambers', through='articles.LikeArticle', to='articles.article'),
        ),
    ]
