# Generated by Django 5.0.6 on 2024-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_content'),
        ('members', '0005_member_liking_article_mambers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='liking_article_mambers',
        ),
        migrations.AddField(
            model_name='member',
            name='liking_article_members',
            field=models.ManyToManyField(related_name='liking_article_members', through='articles.LikeArticle', to='articles.article'),
        ),
    ]
