# Generated by Django 5.0.6 on 2024-06-09 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_card'),
        ('members', '0006_remove_member_liking_article_mambers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cards',
            field=models.ManyToManyField(related_name='related_to_card', through='friends.Card', to=settings.AUTH_USER_MODEL),
        ),
    ]
