# Generated by Django 5.0.6 on 2024-06-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='constellation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
